seed: 42
numGroups: 8
growthRate: 32
currentDir: ${hydra:runtime.cwd}

# MARK: - transformer
hiddenDims: 512
numHead: 8
numEncoderLayer: 6
numDecoderLayer: 6
dimFeedForward: 2048
dropout: .1
numQuery: 80
numClass: 4
numBlocks:
  - 6
  - 6
  - 6
  - 6

# MARK: - dataset
targetHeight: 608
targetWidth: 608

# MARK: - miscellaneous
device: cuda
weight: ""
#weight: ${hydra:runtime.cwd}/checkpoint/mango.pt


# MARK: - training config
lr: 1e-6
lrBackbone: 1e-5
batchSize: 8
weightDecay: 1e-4
epochs: 12
lrDrop: 1000
clipMaxNorm: .1

# MARK: - loss
classCost: 1.
bboxCost: 5.
giouCost: 2.
eosCost: .1

# MARK: - dataset
dataDir: ${hydra:runtime.cwd}/data
trainAnnFile: ${hydra:runtime.cwd}/data/small/Test.json
valAnnFile: ${hydra:runtime.cwd}/data/small/Valid.json
testAnnFile: ${hydra:runtime.cwd}/data/Test.json

# MARK: - miscellaneous
outputDir: ${hydra:runtime.cwd}/checkpoint
taskName: DETR
numWorkers: 1
multi: False
amp: False

# MARK: - wandb
wandbEntity: marcoparola
wandbProject: conditioning-transformer

scaleMetadata:
  Wind Speed:
    - 0
    - 20
  Wind Direction:
    - 0
    - 360
  Temperature:
    - -20
    - 40
  Humidity:
    - 0
    - 100
  Precipitation latest 10 min:
    - 0
    - 5
  Dew Point:
    - -15
    - 20
  Sun Radiation Intensity:
    - 0
    - 1100
  Min of sunshine latest 10 min:
    - 0
    - 10
  Hour:
    - 0
    - 23
  Month:
    - 1
    - 12