defaults:
  - _self_
  - metadataScaling
  - enhancer
  - yolos
  
seed: 42
numGroups: 8
growthRate: 32
currentDir: ${hydra:runtime.cwd}

# MARK: - transformer
model: null
dummy: False
hiddenDims: 512
numHead: 8
numEncoderLayer: 6
numDecoderLayer: 6
dimFeedForward: 2048
dropout: .1
numQuery: 80
numClass: 4
numBlocks:
  - 6
  - 6
  - 6
  - 6

# MARK: - yolo dataset
targetHeight: 608
targetWidth: 608

# MARK: - miscellaneous
device: cuda
weight: ""


# MARK: - training config
lr: 1e-6
lrBackbone: 1e-5
batchSize: 16
weightDecay: 1e-4
epochs: 100
lrDrop: 1000
clipMaxNorm: .1
patience: 25

# MARK: - loss
classCost: 1.
bboxCost: 5.
giouCost: 2.
eosCost: .1

# MARK: - dataset
dataDir: ${hydra:runtime.cwd}/data
trainAnnFile: ${hydra:runtime.cwd}/data/orig/Train.json
valAnnFile: ${hydra:runtime.cwd}/data/orig/Valid.json
testAnnFile: ${hydra:runtime.cwd}/data/orig/Test.json

# MARK: - miscellaneous
outputDir: ${hydra:runtime.cwd}/checkpoint
taskName: DETR
numWorkers: 1
multi: False
amp: False

# MARK: - wandb
wandbEntity: marcoparola
wandbProject: conditioning-transformer

inference:
  savePlot: False
  showPlot: False
  savePrediction: False
