numMetadata: 10
sequenceLength: 10

scaleMetadata:
  Wind Speed:
    - 0
    - 20
  Wind Direction:
    - 0
    - 360
  Temperature:
    - -20
    - 40
  Humidity:
    - 0
    - 100
  Precipitation latest 10 min:
    - 0
    - 5
  Dew Point:
    - -15
    - 20
  Sun Radiation Intensity:
    - 0
    - 1100
  Min of sunshine latest 10 min:
    - 0
    - 10
  Hour:
    - 0
    - 23
  Month:
    - 1
    - 12